andy/cadastro/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('cadastro.views',
        url(r'registrar/$', 'register', name='cadastro_register'),
        url(r'perfil/ativar/(?P<activation_key>\w+)/$', 'activate', name='cadastro_activate'),
        url(r'perfil/$', 'profile', name='cadastro_profile'),
        url(r'pesquisa/$', 'survey', name='cadastro_survey'),
        url(r'anuidade/$', 'pay', name='cadastro_pay'),
)

andy/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django_pagseguro.urls import pagseguro_urlpatterns
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from cadastro.forms import PasswordResetForm

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),
    url(r'^password/reset/$', password_reset, { 'template_name': 'password_reset.html',
                                                'email_template_name': 'emails/password_reset.txt',
                                                'from_email': 'no-reply@ciclocidade.org.br',
                                                'password_reset_form': PasswordResetForm}, name='password_reset'),
    url(r'^password/done/$', password_reset_done, { 'template_name': 'password_reset_done.html'}, name='password_reset_done'),
    url(r'^password/confirm/(?P<uidb36>\w+)/(?P<token>[\w-]+)/$', password_reset_confirm, { 'template_name': 'password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^password/complete/$', password_reset_complete, { 'template_name': 'password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^$', 'andy.views.login', name="index"),
    url(r'^', include('cadastro.urls')),
)

urlpatterns += pagseguro_urlpatterns()

andy/cadastro/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

EDUCATIONS = (
        ('FI', u'Fundamental Incompleto'),
        ('FC', u'Fundamental Completo'),
        ('MI', u'Médio Incompleto'),
        ('MC', u'Médio Completo'),
        ('SI', u'Superior Incompleto'),
        ('SC', u'Superior Completo'),
        ('MD', u'Mestrado/Doutorado'),
    )

class Member(models.Model):
    user = models.OneToOneField(User)
    created_at = models.DateTimeField(u"Data de cadastro", auto_now_add=True)
    sexo = models.CharField(u"Sexo", choices=(("F", "Feminino"), ("M", "Masculino")), max_length=2)
    birth = models.DateField(u"Data de Nascimento", null=True)
    phone_number = models.CharField(u"Telefone", max_length=15)
    address_street = models.CharField(u"Endereço", max_length=150)
    address_state = models.CharField(u"Estado", max_length=30)
    address_city = models.CharField(u"Cidade", max_length=30)
    address_zip = models.CharField(u"CEP", max_length=9)
    address_etc = models.CharField(u"Complemento", max_length=50, blank=True, default='')
    education = models.CharField(u'Escolaridade', max_length=2, choices=EDUCATIONS)
    profession = models.CharField(u'Profissão/Ocupação', max_length=100)
    rg = models.CharField(u'Documento de identidade', max_length=15)
    id_type = models.CharField(u"Tipo do documento", choices=(("RG", "RG"), ("RNE", "RNE")), max_length=4)
    cpf = models.CharField(u'CPF', max_length=15)
    organizations = models.TextField(u"Organizações", default="", blank=True, null=True)
    receive_news = models.BooleanField(u'Recebe informativo', default=True, blank=True)

    class Meta:
        verbose_name = "Associado"
    
    def answered_survey(self):
        try:
            BikeUsageSurvey.objects.get(member=self)
        except BikeUsageSurvey.DoesNotExist:
            return False
        return True

    def paid(self):
        return bool(self.user.payment_set.filter(paid=True).count())

    def city_uf_str(self):
        return "%s/%s" % (self.address_city, self.address_state)
    
    def is_complete(self):
        required_fields = ( 'user',
                            'created_at',
                            'sexo',
                            'birth',
                            'phone_number',
                            'address_street',
                            'address_state',
                            'address_city',
                            'address_zip',
                            'education',
                            'cpf')
        return all(getattr(self, field) for field in required_fields)

    def __unicode__(self):
        return self.name

    @property
    def name(self):
        return self.user.get_full_name()

    @property
    def email(self):
        return self.user.email


from multiselectmodelfield import MultiSelectField
class BikeUsageSurvey(models.Model):
    FREQUENCY_CHOICES = [ (str(i),label) for i,label in enumerate((u"5 a 7 vezes por semana",
                         u"2 a 4 vezes por semana",
                         u"uma vez por semana",
                         u"eventualmente",
                         u"não utilizo a bicicleta")) ]
    SOURCE_CHOICES = [ (str(i),label) for i,label in enumerate((u"sites, blogs ou mecanismos de busca na internet",
                      u"facebook, twitter ou listas de e-mail",
                      u"indicação de amigos / conhecidos",
                      u"eventos / atividades",
                      u"panfleto",
                      u"participei do ato de fundação",
                      u"instituição ou grupo",
                      u"outros")) ]
    USAGE_CHOICES = [ (str(i),label) for i,label in enumerate((
                     u"ir ao trabalho às vezes",
                     u"ir ao trabalho todos os dias",
                     u"fazer outros deslocamentos no meu dia-a-dia",
                     u"como instrumento de trabalho (ex: entregas, vigilância, etc)",
                     u"lazer",
                     u"esporte (amador ou profissional)",
                     u"não utilizo a bicicleta")) ]
    EXPECTATIONS_CHOICES = [ (str(i),label) for i,label in enumerate((
                    u"conhecer direitos e leis a serem defendidos junto a órgãos públicos e outras instituições",
                    u"contribuir para a construção de políticas públicas relativas à mobilidade urbana",
                    u"espaços de discussão sobre o uso da bicicleta na cidade (dicas, problemas, experiências, trajetos e outros)",
                    u"atividades culturais e educativas que promovam o uso da bicicleta (encontros, passeios, seminários, oficinas)",
                    u"aprofundamento teórico, estudo e produção de conhecimento",
                    u"conhecer dicas e técnicas sobre compra, uso e manutenção de bicicletas")) ]
    VOLUNTEERING_CHOICES = [ (str(i),label) for i,label in enumerate((
                    u"sim, participando de projetos específicos e pontuais nas minhas áreas de interesse ou atuação",
                    u"sim, participando da Área de Cultura da Bicicleta e Formação do Ciclista",
                    u"sim, participando da Área de Participação Pública",
                    u"sim, participando da Área de Pesquisa",
                    u"sim, participando da Área de Comunicação",
                    u"sim, participando da Área de Tecnologia",
                    u"sim, participando da Área de Relações com Associados e Voluntários",
                    u"sim, participando da Área de Desenvolvimento Institucional",
                    u"não, não tenho disponibilidade")) ]
    CITY_REGION = [ (str(i),label) for i,label in enumerate((
		    u"ARICANDUVA (Aricanduva, Carrão, Vila Formosa)",
		    u"BUTANTÃ (Butantã, Morumbi, Vila Sônia, Raposo Tavares, Rio Pequeno)",
		    u"CAMPO LIMPO, Campo Limpo, Capão Redondo, Vila Andrade)",
		    u"CAPELA DO SOCORRO (Socorro, Grajaú, Cidade Dutra)",
		    u"CASA VERDE (Casa Verde, Cachoeirinha, Limão)",
		    u"CIDADE ADEMAR (Cidade Ademar, Pedreira)",
		    u"CIDADE TIRADENTES (Cidade Tiradentes)",
		    u"ERMELINO MATARAZZO (Ermelino Matarazzo, Ponte Rasa)",
		    u"FREGUESIA DO Ó (Freguesia do Ó, Brasilândia)",
		    u"GUAIANASES (Guaianases, Lajeado)",
		    u"IPIRANGA (Ipiranga, Cursino, Sacomã)",
		    u"ITAIM PAULISTA (Itaim Paulista, Vila Curuçá)",
		    u"ITAQUERA (Itaquera, Parque do Carmo, José Bonifácio, Cidade Líder)",
		    u"JABAQUARA (Jabaquara)",
		    u"JAÇANÃ (Tremembé, Jaçanã)",
		    u"LAPA (Lapa, Barra Funda, Perdizes, Vila Leopoldina, Jaguaré, Jaraguá)",
		    u"M'BOI MIRIM (Jardim Ângela, Jardim São Luís)",
		    u"MÓOCA (Mooca, Brás, Belém, Pari, Água Rasa, Tatuapé)",
		    u"PARELHEIROS (Parelheiros, Marsilac)",
		    u"PENHA (Penha, Cangaíba, Vila Matilde, Artur Alvim)",
		    u"PERUS (Anhangüera, Perus)",
		    u"PINHEIROS (Alto de Pinheiros, Pinheiros, Itaim Bibi, Jardim Paulista)",
		    u"PIRITUBA (Pirituba, São Domingos, Jaraguá)",
		    u"SANTANA (Santana, Tucuruvi, Mandaqui)",
		    u"SANTO AMARO (Santo Amaro, Campo Belo, Campo Grande)",
		    u"SÃO MATEUS (São Mateus, São Rafael, Iguatemi)",
		    u"SÃO MIGUEL (São Miguel Paulista, Jardim Helena, Vila Jacuí)",
		    u"SÉ (Bom Retiro, Santa Cecília, Consolação, República, Sé, Bela Vista, Liberdade, Cambuci)",
		    u"VILA MARIA (Vila Maria, Vila Guilherme, Vila Medeiros)",
		    u"VILA MARIANA (Vila Mariana, Saúde, Moema)",
		    u"VILA PRUDENTE (Vila Prudente, Sapopemba, São Lucas)",
            u"Outros municípios da grande São Paulo")) ]

    member = models.OneToOneField(Member, verbose_name="Associado")
    created_at = models.DateTimeField(u"Data", auto_now_add=True)
    bike_usage = MultiSelectField(u"Uso da bicicleta", choices=USAGE_CHOICES)
    frequency = models.CharField(u"Frequência que usa a bicicleta", choices=FREQUENCY_CHOICES, max_length=255)
    source = models.CharField(u"Como soube da associação", choices=SOURCE_CHOICES, max_length=255)
    expectations = MultiSelectField(u"Expectativa Ciclocidade", choices=EXPECTATIONS_CHOICES)
    city_region = MultiSelectField("Por onde você pedala (SUBPREFEITURAS / distritos)", choices=CITY_REGION, default="", blank=True)
    volunteering = MultiSelectField(u"Voluntário", choices=VOLUNTEERING_CHOICES)
    
    class Meta:
        verbose_name = u"Pesquisa hábitos e interesses"
        verbose_name_plural = u"Pesquisas hábitos e interesses"

    def __unicode__(self):
        return self.member.name

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^cadastro\.multiselectmodelfield\.MultiSelectField"])

andy/cadastro/views.py
# coding: utf-8

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.conf import settings

from registration.forms import RegistrationFormUniqueEmail
from registration.models import RegistrationProfile

from pagamento.models import Payment

from cadastro.models import Member, BikeUsageSurvey
from cadastro.forms import MemberForm, BikeUsageForm

from datetime import datetime, date

import random

def register(request):
    if request.method == 'POST':
        username = request.POST['email'].replace('.', '').replace('_', '').replace('-', '').split('@')[0]
        while True:
            try: 
                User.objects.get(username=username)
                username += str(random.randint(0,9))
            except User.DoesNotExist:
                break
        d = {   'username': username,
                'email': request.POST['email'],
                'csrfmiddlewaretoken': request.POST['csrfmiddlewaretoken'],
                'password1': request.POST['password1'],
                'password2': request.POST['password2']}
        form = RegistrationFormUniqueEmail(data=d)
        if form.is_valid():
            new_user = form.save()
            messages.add_message(request, messages.SUCCESS, 'Registro feito com sucesso, por favor verifique seu email para continuar com o processo de associação.')
            return HttpResponseRedirect('/')
    else: 
        form = RegistrationFormUniqueEmail()
    return render_to_response('register.html', {'form': form}, context_instance=RequestContext(request))

def activate(request, activation_key=None):
    if activation_key:
        activation_key = activation_key.lower() 
        user = RegistrationProfile.objects.activate_user(activation_key)
        if user:
            messages.add_message(request, messages.SUCCESS, 'Seu email foi verificado com sucesso! Faça o login para continuar com o processo de associação.')
            return HttpResponseRedirect(reverse(profile))
    messages.add_message(request, messages.ERROR, 'Não foi possivel ativar o cadastro')
    return render_to_response('activate_error.html', context_instance=RequestContext(request))

@login_required
def profile(request):
    msg = ''
    try:
        member = request.user.get_profile()
        msg = u'Olá %s! Atualize os seus dados cadastrais :-)' % request.user.get_full_name()
    except ObjectDoesNotExist:
        member = Member(user=request.user)
    if request.method == 'POST':
        form = MemberForm(request.POST, instance=member)
        if form.is_valid():
            member = form.save()
            messages.add_message(request, messages.SUCCESS, 'Seu perfil foi atualizado com sucesso!')
            if member.is_complete() and request.user.is_active:
                try:
                    BikeUsageSurvey.objects.get(member=member)
                    return HttpResponseRedirect(reverse("cadastro_pay"))
                except BikeUsageSurvery.DoesNotExist:
                    return HttpResponseRedirect(reverse('cadastro_survey'))
    else:
        form = MemberForm(instance=member)
    if not member.is_complete():
        msg = "Complete os dados do seu perfil!"
    if not form.fields['name'].initial:
        form.fields['name'].initial = request.user.get_full_name()
    if not form.fields['address_city'].initial:
        form.fields['address_city'].initial = u'São Paulo' 
    messages.add_message(request, messages.WARNING, msg)
    return render_to_response('profile.html', {'user': request.user, 'form': form}, context_instance=RequestContext(request))

def _has_profile(user):
    try:
        user.get_profile().is_complete()
    except ObjectDoesNotExist:
        return False
    return True

@login_required
@user_passes_test(_has_profile, login_url='/perfil/')
def survey(request):
    member = request.user.get_profile()
    form = None
    if not member.answered_survey():
        form = BikeUsageForm()
    if request.method == 'POST':
        form = BikeUsageForm(request.POST)
        if form.is_valid():
            try:
                BikeUsageSurvey.objects.get(member=member)
            except BikeUsageSurvey.DoesNotExist:
                bus = form.save(commit=False)
                bus.member = member
                bus.save()
                messages.add_message(request, messages.SUCCESS, 'Pesquisa preenchida com sucesso, obrigado!')
                return HttpResponseRedirect(reverse("cadastro_pay"))
            else:
                messages.add_message(request, messages.ERROR, 'Você já preencheu essa pesquisa!')
    return render_to_response('survey.html', {'user': request.user, 'form': form}, context_instance=RequestContext(request))

@login_required
@user_passes_test(_has_profile, login_url='/perfil/')
def pay(request):
    from django_pagseguro.pagseguro import ItemPagSeguro, CarrinhoPagSeguro
    user = request.user
    member = user.get_profile()
    if request.method == 'POST':
        p = Payment.objects.create(status="Aguardando", user=user)
        carrinho = CarrinhoPagSeguro(ref_transacao=p.pk)
        carrinho.set_cliente(email=user.email, cep=member.address_zip)
        valor = calculate_membership_fee(datetime.today())
        donations = request.POST['donation'].replace(",", ".")
        try:
            donations = float(donations)
        except ValueError: 
            donations = 0
        carrinho.add_item(ItemPagSeguro(cod=1, descr='Anuidade Ciclocidade', quant=1, valor=float(valor)))
        if donations > 0:
            carrinho.add_item(ItemPagSeguro(cod=1, descr='Doação Ciclocidade', quant=1, valor=float(donations)))
        payment_form = carrinho.form()
        return render_to_response("pay-forward.html", {'payment_form': payment_form}, context_instance=RequestContext(request))
    paids = user.payment_set.filter(paid=True)

    now = datetime.now()
    year = now.year if now.month >= 8 else now.year - 1
    last_year = paids.filter(created_at__gt=date(year, 8, 1))
    
    show_form = not bool(last_year.count())
    if not show_form:
        messages.add_message(request, messages.SUCCESS, 'Você esta em dia com o pagamento da anuidade!')
        year = None
    else:
        messages.add_message(request, messages.WARNING, 'Por favor, leia as instruções e efetue o pagamento da anuidade via PagSeguro')
        year = datetime.now().year
    return render_to_response("pay.html", {'paids': paids, 'show_form': show_form,  'year': year},
            context_instance=RequestContext(request))

def calculate_membership_fee(date):
    month = date.month
    if month < 8:
        return (8 - month) * 5
    return (12 - month + 8) * 5

andy/cadastro/templates/activate.html
{% extends 'base.html' %}

{% block content %}
<div class="explanation">
	<p><a href="{% url cadastro_survey %}">Responda nossa pesquisa</a></p>
	<p>Obrigado por ter completado sua inscrição. Assim que o pagamento da anuidade for confirmado você receberá um e-mail confirmando seu cadastro e mais informações sobre como participar das atividades do grupo.</p>
	<p>Além da anuidade, você também pode colaborar com o fortalecimento da Ciclocidade doando idéias, tempo como voluntário ou dinheiro. Sugestões e projetos podem ser discutidos no fórum do grupo, ao qual você terá acesso assim que receber a confirmação. Mais informações sobre como atuar como voluntário também serão enviadas por correio eletrônico.</p>
	<p>Contribuições financeiras podem ser feitas por pessoas físicas ou jurídicas diretamente na conta da associação, cujos dados estão abaixo. Até quem não é associado pode ajudar; se você souber de alguém ou alguma empresa que possa se interessar em colaborar, pedimos a gentileza de que encaminhe essa ideia.</p>
</div>
{% endblock %}

andy/cadastro/templates/activate_error.html
{% extends 'base.html' %}

{% block content %}
<div class="explanation">
	<center>
		<h3>Erro ao tentar ativar conta, verifique se o link acessado esta correto.</h3>
	</center>
</div>
{% endblock %}

andy/cadastro/templates/pay-forward.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=latin-1" />
</head>
<body onload="document.forms[0].submit()">
<p>Você será encaminhado para o Pagseguro.</p>
<p>Por favor aguarde...</p>

{{ payment_form }}

</body>
</html>

andy/cadastro/templates/pay.html
{% extends 'base.html' %}

{% block content %}

<ul id="pay">
<li>A Ciclocidade acredita no apoio e na participação de seus associados para cumprir sua missão de transformar São Paulo em um ambiente adequado e seguro ao ciclista.</li>
<li>Nossa entidade não tem fins lucrativos, mas a sua contribuição nos ajuda a manter o custo mínimo de funcionamento.</li>
<li>Seguindo resoluções <a target="_blank" href="http://www.ciclocidade.org.br/quem-somos/estatuto">estatutárias</a> e deliberações da Diretoria, a partir de maio de 2012, a Ciclocidade passará a contar com uma contribuição associativa paga anualmente por seus associados e de maneira proporcional aos meses restantes até a data de renovação.</li>
<li>A renovação acontece no mês de agosto, quando é cobrado o valor integral de R$ 60.</li>
<li>Caso você esteja se associando nos demais meses do ano, o valor cobrado será proporcionalmente menor. Por exemplo: ao se associar no mês de maio, o pagamento será de R$ 15; no mês de junho, o valor será de R$10 e assim por diante. </li>
<li>O pagamento pode ser feito através de boleto bancário, cartão de crédito, débito em conta ou outras formas disponíveis no serviço PagSeguro.</li>
<li>Em até 48 horas você receberá um e-mail de boas-vindas da Ciclocidade, confirmando a o seu pedido de associação.</li>
<li>Você também poderá doar doar outros valores além da sua contribuição associativa. Para isso, preencha o campo “doações adicionais” antes de completar o seu pedido.</li>
</ul>

{% if show_form %}
<form action="." method="post" name="payment">
	{% csrf_token %}
	<div class="form" style="margin-left: 18px;">
	<label for="donation">Doações adicionais (digite o valor em reais): </label><input id="donation" type="text" name="donation" value="0,00" style="width: 80px;" />

	</div>
	<input style="margin-left: 20px;" type="image" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/205x30-pagar.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
</form>
{% endif %}
{% if paids %}
<h2>Anuidades pagas:</h2>

<ul>
{% for paid in paids %}
<li>{{ paid }}</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

andy/cadastro/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div id="profile_form" class="form">
<form id="profile" action="" method="post" accept-charset="UTF-8">
{% csrf_token %}
<fieldset id="main_fieldset">
<legend>Editar perfil</legend>
<h3>Sua conta</h3>
<span class="short_explanation">Se quiser alterar a sua senha preencha os campos abaixo</span><br/>

{% if form.non_field_errors %}<span class="form_error">{% for error in form.non_field_errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
<div style="float: left; width: 242px;">
<div class="container">
<label for="username">nome completo: </label><br/>
<p style="margin-top: 4px; margin-botom: 4px;">{{user.get_full_name}}</p>
</div>
<div class="container">
    <label for="email" >endereço de email:</label><br/>
<p style="margin-top: 4px; margin-botom: 4px;">{{user.email}}</p>
</div>
</div>
<div style="float: right; width: 242px;">
<div class="container">
    <label for="id_password1" >{{form.password1.label}}:</label><br/>
    {% if form.password1.errors %}<span class="form_error">{% for error in form.password1.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.password1}}<br/>
</div>
<div class="container">
    <label for="id_password2" >{{form.password2.label}}:</label><br/>
    {% if form.password2.errors %}<span class="form_error">{% for error in form.password2.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.password2}}<br/>
</div>
</div>

<div class="line-breaker">
</div>

<h3>Seus dados</h3>
<div style="float: left; width: 242px;">
<div class="container">
    <label for="name" >{{form.name.label}}:</label><br/>
    {% if form.name.errors %}<span class="form_error">{% for error in form.name.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.name}}<br/>
</div>
<div class="container">
    <label for="birth" >{{form.birth.label}}:</label><br/>
    {% if form.birth.errors %}<span class="form_error">{% for error in form.birth.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.birth}}<br/>
</div>

<div class="container sexo">
    <label for="id_sexo" >{{form.sexo.label}}:</label><br/>
    {% if form.sexo.errors %}<span class="form_error">{% for error in form.sexo.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.sexo}}<br/>
</div>
<div class="container">
    <label for="cpf" >{{form.cpf.label}}:</label><br/>
    {% if form.cpf.errors %}<span class="form_error">Número de CPF inválido.</span>{% endif %}
    {{form.cpf}}<br/>
</div>
<div class="container">
    <label for="id_rg" >{{form.rg.label}}:</label><br/>
    {% if form.rg.errors %}<span class="form_error">{% for error in form.rg.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.rg}}<br/>
</div>
<div class="container sexo">
    <label for="id_id_type" >{{form.id_type.label}}:</label><br/>
    {% if form.id_type.errors %}<span class="form_error">{% for error in form.id_type.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.id_type}}<br/>
</div>
<div class="container">
    <label for="phone_number" >{{form.phone_number.label}}:</label><br/>
    {% if form.phone_number.errors %}<span class="form_error">{% for error in form.phone_number.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.phone_number}}<br/>
</div>
</div>
<div style="float: right; width: 242px;">
<div class="container">
    <label for="id_education" >{{form.education.label}}:</label><br/>
    {% if form.education.errors %}<span class="form_error">{% for error in form.education.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.education}}<br/>
</div>
<div class="container">
    <label for="address_street" >{{form.address_street.label}}:</label><br/>
    {% if form.address_street.errors %}<span class="form_error">{% for error in form.address_street.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.address_street}}<br/>
</div>
<div class="container">
    <label for="address_etc" >{{form.address_etc.label}}:</label><br/>
    {% if form.address_etc.errors %}<span class="form_error">{% for error in form.address_etc.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.address_etc}}<br/>
</div>
<div class="container">
    <label for="address_state" >{{form.address_state.label}}:</label><br/>
    {% if form.address_state.errors %}<span class="form_error">{% for error in form.address_state.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.address_state}}<br/>
</div>
<div class="container">
    <label for="address_city" >{{form.address_city.label}}:</label><br/>
    {% if form.address_city.errors %}<span class="form_error">{% for error in form.address_city.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.address_city}}<br/>
</div>
<div class="container">
    <label for="address_zip" >{{form.address_zip.label}}:</label><br/>
    {% if form.address_zip.errors %}<span class="form_error">Informe um código postal no formato XXXXX-XXX.<br/></span>{% endif %}
    {{form.address_zip}}<br/>
</div>
<div class="container">
    <label for="id_profession" >{{form.profession.label}}:</label><br/>
    {% if form.profession.errors %}<span class="form_error">{% for error in form.profession.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.profession}}<br/>
</div>
</div>
<div class="container" style="clear: both; width: 475px;">
	<label for="id_receive_news" >{{form.organizations.label}}</label> <br />
	{% if form.organizations.errors %}<span class="form_error">{% for error in form.organizations.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
	{{form.organizations}} <br />
</div>
<div class="container" style="clear: both;">
    {% if form.receive_news.errors %}<span class="form_error">{% for error in form.receive_news.errors %}{{ error|escape }}<br/>{% endfor %}</span>{% endif %}
    {{form.receive_news}} <label for="id_receive_news" >{{form.receive_news.label}}</label> <br />
</div>
<div style="float: right;">
    <label for="submit" ></label><br/>
    <input type="submit" value="Salvar" />
</div>
<script type="text/javascript">
	$("#id_birth").mask("99/99/9999");
	$("#id_address_zip").mask("99999-999");
	$("#id_cpf").mask("999.999.999-99");
	$("#id_phone_number").mask("99-99999999?9");
</script>

</fieldset>
</form>
</div>
{% endblock %}